[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["storageLayout", "metadata"]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15
fail_on_revert = false

[profile.default.metadata]
bytecode_hash = "none"

[rpc_endpoints]
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
worldchain_sepolia = "${WORLDCHAIN_SEPOLIA_RPC_URL}"
worldchain_mainnet = "${WORLDCHAIN_MAINNET_RPC_URL}"

[etherscan]
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}" }
worldchain_sepolia = { key = "${WORLDCOIN_API_KEY}" }
worldchain_mainnet = { key = "${WORLDCOIN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options 